# Pytorch Refresher

## Basic Pytorch

### Import PyTorch

In [1]:
import torch
print(torch.__version__)

2.0.1


### PyTorch Tensors

#### Scalar - 0D Tensor

In [5]:
# Create a scalar (0-dimensional) tensor
scalar_tensor = torch.tensor(42)
print("Scalar Tensor:",scalar_tensor)

Scalar Tensor: tensor(42)


In [6]:
# Dimension of Tensor
scalar_tensor.ndim

0

In [7]:
# Get python number from tensor
scalar_tensor.item()

42

#### Vector - 1D Tensor

In [8]:
# Create a 1-dimensional tensor
vector_tensor = torch.tensor([1, 2, 3, 4, 5])

In [11]:
print("Dimension of Vector:", vector_tensor.ndim)
print("Shape of Vector:", vector_tensor.shape)

Dimension of Vector: 1
Shape of Vector: torch.Size([5])


#### Matrix - 2D Tensor

In [13]:
# Create a 2-dimensional tensor (matrix)
matrix_tensor = torch.tensor([[1, 2], [3, 4]])

print(matrix_tensor)

tensor([[1, 2],
        [3, 4]])


In [15]:
print("Dimension of Matrix:", matrix_tensor.ndim)
print("Shape of Matrix:", matrix_tensor.shape)

Dimension of Matrix: 2
Shape of Matrix: torch.Size([2, 2])


### Tensors - Multidimension

In [19]:
# Create a 3-dimensional tensor
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor_3d)

# You can also specify the data type (dtype) explicitly
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float)
print(float_tensor)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([1., 2., 3.])


#### Random Tensor

In [23]:
random_tensor = torch.rand(size=(3,4))
print(random_tensor)
print(random_tensor.dtype)

tensor([[0.2024, 0.6972, 0.2207, 0.0172],
        [0.5808, 0.5810, 0.9928, 0.6064],
        [0.1130, 0.3650, 0.8337, 0.6050]])
torch.float32


### PyTorch Arithmetic

In [10]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Addition
c = a + b  # or torch.add(a, b)
print("c = a + b =",c)

# Subtraction
d = a - b  # or torch.subtract(a, b)
print("d = a - b =",d)

# Element-wise multiplication
e = a * b  # or torch.mul(a, b)
print("e = a * b =",e)

# Element-wise division
f = a / b  # or torch.div(a, b)
print("f = a / b =",f)

# Element-wise exponentiation
g = torch.pow(a, 2)  # Square each element of 'a'
print("g = a ^ b =",g)

# Element-wise square root
h = torch.sqrt(a)
print("h = sqrt(a) =",h)

c = a + b = tensor([5, 7, 9])
d = a - b = tensor([-3, -3, -3])
e = a * b = tensor([ 4, 10, 18])
f = a / b = tensor([0.2500, 0.4000, 0.5000])
g = a ^ b = tensor([1, 4, 9])
h = sqrt(a) = tensor([1.0000, 1.4142, 1.7321])


### Neural Network Arechitecture


In [2]:
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.conv1 = nn.Conv2d(3, 16, 3, padding=1)
        self.relu = nn.ReLU()
        self.pool = nn.MaxPool2d(2, 2)
        self.fc1 = nn.Linear(16 * 16 * 16, 10)  # Assuming 32x32 input images and 10 output classes

    def forward(self, x):
        x = self.pool(self.relu(self.conv1(x)))
        x = x.view(-1, 16 * 16 * 16)
        x = self.fc1(x)
        return x


### MNIST Classification

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F